spring.datasource.url=jdbc:postgresql://postgres:5432/usermanager
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.graphql.graphiql.enabled=true
spring.application.name=usermanager
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql